language: en
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "EntitySynonymMapper"
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: "DIETClassifier"
#  epochs: 50
#  ranking_length: 5
##- name: DucklingHTTPExtractor
 ## url: http://localhost:8000
 ## dimensions:
 ## - email
 ## - number
 ## - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
policies:
- name: TEDPolicy
  max_history: 5
  epochs: 20
  batch_size:
  - 32
  - 64
- max_history: 5
  name: AugmentedMemoizationPolicy
- core_threshold: 0.3
  name: TwoStageFallbackPolicy
  nlu_threshold: 0.6
- name: FormPolicy
- name: MappingPolicy